# Meta Data for SEO

## Homepage
title = "CSSUI"
titleSeparator = "-"
titleAddition = "Interactive Components Library in Pure CSS"
description = "CSSUI is a library of interactive components realized in pure CSS"

## Open Graph
images = ["doks.png"]
ogLocale = "en_US"
domainTLD = "cssui.dev"
titleHome = "CSSUI"

## Twitter Cards
twitterSite = "@getdoks"
twitterCreator = "@henkverlinde"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "CSSUI"
schemaAuthor = "Francesco Improta"
schemaAuthorTwitter = "https://twitter.com/zetareticoli"
# schemaAuthorLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
schemaAuthorGitHub = "https://github.com/zetareticoli"
schemaLocale = "en-US"
schemaLogo = "logo-doks.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "doks.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/cssui"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/zetareticoli/cssui"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"
copyRight = "Copyright (c) 2021-2021 Francesco Improta"

# Alert
alert = false
alertText = "Like Doks? <a class=\"alert-link\" href=\"https://github.com/h-enk/doks/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/zetareticoli/cssui"
editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = false
  kaTex = false
  collapsibleSidebar = false
